# -*- mode: ruby -*-
# # vi: set ft=ruby :

# Basically following the default installation instructions:
# http://docs.docker.io/en/latest/installation/ubuntulinux/
$script = <<SCRIPT
   apt-get -y install git curl
   curl https://get.docker.io/gpg | apt-key add -
   echo deb http://get.docker.io/ubuntu docker main > /etc/apt/sources.list.d/docker.list
   apt-get -y update
   apt-get -y install lxc-docker linux-image-generic-lts-raring linux-headers-generic-lts-raring
   usermod -a -G docker vagrant
   reboot
SCRIPT

VAGRANTFILE_API_VERSION = "2"

box      = 'precise64'
url      = 'http://cloud-images.ubuntu.com/vagrant/precise/current/precise-server-cloudimg-amd64-vagrant-disk1.box'
# url = 'http://files.vagrantup.com/precise64.box'
# This box comes with a docker ready kernel: http://www.vagrantbox.es/

hostname = 'docker-host'
domain   = 'kalrsn.com'
ip       = '192.168.50.42'
ram      = '1024'


Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

   config.vm.box = box
   config.vm.box_url = url  
   config.vm.host_name = hostname
   config.vm.network :hostonly, ip   

   config.vm.customize [
      'modifyvm', :id,
      '--name', hostname,
      '--memory', ram
   ]

   config.vm.provision 'shell', inline: $script   
   
end