# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
   config.vm.box = "raring64"
   config.vm.box_url = "http://goo.gl/Y4aRr" #raring64
   config.vm.synced_folder "sharedir", "/home/vagrant/sharedir"
   config.ssh.forward_x11 = true
   config.vm.network "forwarded_port", guest: 80, host: 8080, auto_correct: true
   config.vm.network "private_network", ip: "192.168.10.3"
   config.vm.provider :virtualbox do |virtualbox|
      virtualbox.customize ["modifyvm", :id, "--name", "PrimeMiner"]
      virtualbox.customize ["modifyvm", :id, "--memory", "1024"]
      #virtualbox.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      #virtualbox.customize ["setextradata", :id, "--VBoxInternal2/SharedFoldersEnableSymlinksCreate/v-root", "1"]
  end
  config.vm.provision :shell, :inline => $startup  
end

$startup = <<EOF
   #basic tools 
   sudo apt-get update
   sudo apt-get install -y libboost-all-dev libdb++-dev libgmp-dev
   sudo apt-get install -y libssl-dev dos2unix
   sudo apt-get install -y build-essential
   sudo apt-get install -y screen
   sudo apt-get install -y git
   sudo apt-get install -y curl
   sudo apt-get install -y x11-apps
    
   #download Primeminer and compile 
   git clone https://github.com/tandyuk/jhPrimeminer
   cd jhPrimeminer
   make
   mkdir -p $HOME/bin
   cp jhprimeminer $HOME/bin

EOF

